name: Deploy to Github Pages
on: 
  push:
    branches: 
      - 'main'
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '14.x'
      - run: npm config set @bit:registry https://node.bit.dev
      - run: npm install
      - run: npm run deploy